spring.application.name=purchase_order

spring.datasource.url=jdbc:postgresql://localhost:5432/kanishka_purchase_order
spring.datasource.username=postgres
spring.datasource.password=Rup@@.123$
spring.jpa.hibernate.ddl-auto=update